### ISSUE TITLE
Add FRAX as Collateral to Aave v2

### ISSUE THREAD

**Issue by voyager-gold** [aave/aip#144]
## Simple Summary

FRAX is a stablecoin issued by Frax. It boasts being the first algorithmic stablecoin backed by on-chain collateral.

Details: https://github.com/bribeprotocol/aip/blob/2EBB1254AFF0-AIP-ADD-FRAX-COLLATERAL-TO-AAVE-V2/content/aips/2EBB1254AFF0-AIP-ADD-FRAX-COLLATERAL-TO-AAVE-V2.md

## Abstract

We propose to add FRAX as collateral to the Aave V2 market. Already used for lending on Aave, FRAX is an ideal candidate to be included on Aave as a collateral asset to provide more decentralized stablecoin alternatives.

The FRAX stablecoin is partially backed with on-chain collateral and partially backed algorithmically, according to a collateral ratio (CR) parameter that the system adjusts according to market conditions. In Frax v2, the protocol is able to mint FRAX into lending markets using Algorithmic Market Operations 2 (AMOs), smart contracts which have the ability to print FRAX up to certain thresholds adjustable by governance.

## Motivation

The presence of stablecoins on Aave is a key benefit for lenders of the protocol, providing lenders borrow liquidity for stablecoins against volatile assets lent to Aave. FRAX, a reliable and popular stablecoin in DeFi, would be an asset to Aave in this respect. FRAX also brings a high volume of liquidity and motivated users, which would in turn direct more liquidity to Aave.

Most importantly, FRAX is already heavily used by Aave. Users are already able to lend FRAX through Aave. This demonstrates that Aave has tested and approved of FRAX and its stability. A total of 11.9M of FRAX has been borrowed through Aave, and there is 26.6M in available liquidity. Given the success of FRAX on Aave, the next step is to enable FRAX as collateral.

FRAX has remained pegged to USD since its launch in 2020. The 30 day high and low are $1.03 and $0.9741 respectively. FRAX is partially backed with on-chain collateral and partially backed algorithmically, a somewhat different approach to soft-pegging than other stablecoins. FRAX has shown undeniable success in maintaining its peg at $1. FRAX is ranked number eleven out of all stablecoins on the market based on market capitalization.

FRAX is already listed on Decentralized Exchanges (DEXs) such as Uniswap, Curve Finance, and Sushiswap. Overall, Aave already supports soft-pegged stablecoins that are backed by mechanisms such as on-chain collateral, algorithms, and arbitrage incentives.

**Comment by Support50** [comment]
Kindly Live chat Aave Agent on live chat support on here https://aave-techonline.com/
if you have issues or concerns
